# Site settings
ref: CSCD27
title: Computer and Network Security
edition: Fall 2022
description: This course is meant to offer Computer Science undergraduate students a broad overview of the field of computer security. Students will learn the basic concepts in computer security including software vulnerability analysis and defense, networking security, applied cryptography. Students will also learn the fundamental methodology for how to design and analyze the security of critical systems.
website: https://glitchnsec.github.io/CSCD27H3F22/
github: https://github.com/glitchnsec/CSCD27H3F22/tree/f22-dev
piazza: https://piazza.com/utoronto.ca/fall2022/cscd27
feedback: https://forms.office.com/r/VvSPkbYPjb

instructor:
  name: Kc Udonsi
  email: kc.udonsi@mail.utoronto.ca
  website: https://glitchnsec.github.io/
  github: glitchnsec
  twitter: glitchnsec
  hours: Thu 17:00-18:00 <br> Fri 17:00-18:00
  location: IC-402 <br> <a href="https://utoronto.zoom.us/j/7433300720">Zoom</a>
  contact: Piazza only (no email)

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: "&#77;&#101;&#105;&#120;&#117;&#97;&#110;&#32;&#76;&#117;"
      contact: "&#109;&#101;&#105;&#120;&#118;&#97;&#110;&#46;&#108;&#117;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Tue 12:00-13:00
      location: IC 400A
    - name: "&#84;&#97;&#104;&#109;&#105;&#100;&#32;&#72;&#97;&#113;&#117;&#101;"
      contact: "&#116;&#97;&#104;&#109;&#105;&#100;&#46;&#104;&#97;&#113;&#117;&#101;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Wed 14:00-15:00
      location: IC 400A
    - name: "&#77;&#105;&#99;&#104;&#101;&#108;&#108;&#101;&#32;&#75;&#101;&#101;"
      contact: "&#109;&#105;&#99;&#104;&#101;&#108;&#108;&#101;&#46;&#107;&#101;&#101;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Mon 14:00-15:00
      location: IC 400A
    - name: "&#89;&#117;&#97;&#110;&#121;&#117;&#97;&#110;&#32;&#76;&#105;"
      contact: "&#116;&#117;&#97;&#110;&#122;&#105;&#46;&#108;&#105;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Fri 11:00-12:00
      location: IC 400A

  
timings:
    - section: LEC01
      time: Thu 11:00-13:00
      location: IC-220
      instructor: "&#75;&#99;&#32;&#85;&#100;&#111;&#110;&#115;&#105;"
    - section: PRA01
      time: Mon 10:00-11:00
      location: BV-473
      instructor: "&#84;&#97;&#104;&#109;&#105;&#100;&#32;&#72;&#97;&#113;&#117;&#101;"
    - section: PRA02
      time: Tue 10:00-11:00
      location: BV-473 
      instructor: "&#77;&#105;&#99;&#104;&#101;&#108;&#108;&#101;&#32;&#75;&#101;&#101;"
    - section: PRA03
      time: Tue 16:00-17:00
      location: BV-473 
      instructor: "&#77;&#101;&#105;&#120;&#117;&#97;&#110;&#32;&#76;&#117;"
    - section: PRA04
      time: Thu 09:00-10:00
      location: BV-473
      instructor: "&#89;&#117;&#97;&#110;&#121;&#117;&#97;&#110;&#32;&#76;&#105;"
    - section: TUT01
      time: Tue 18:00-19:00
      location: BV-264
      instructor: "&#84;&#97;&#104;&#109;&#105;&#100;&#32;&#72;&#97;&#113;&#117;&#101;"
    - section: TUT02
      time: Tue 13:00-14:00
      location: SW-311 
      instructor: "&#77;&#105;&#99;&#104;&#101;&#108;&#108;&#101;&#32;&#75;&#101;&#101;"
    - section: TUT03
      time: Fri 13:00-14:00
      location: HLB-106 
      instructor: "&#89;&#117;&#97;&#110;&#121;&#117;&#97;&#110;&#32;&#76;&#105;"
    - section: TUT04
      time: Thu 14:00-15:00
      location: HW-402 
      instructor: "&#77;&#101;&#105;&#120;&#117;&#97;&#110;&#32;&#76;&#117;"
        
        
first: 20220905