# Site settings
ref: CSCD27
title: Computer and Network Security
edition: Fall 2022
description: This course is meant to offer Computer Science undergraduate students a broad overview of the field of computer security. Students will learn the basic concepts in computer security including software vulnerability analysis and defense, networking security, applied cryptography. Students will also learn the fundamental methodology for how to design and analyze the security of critical systems.
website: https://glitchnsec.github.io/CSCD27H3F22/
github: https://github.com/glitchnsec/CSCD27H3F22/tree/f22-dev
piazza: https://piazza.com/utoronto.ca/fall2022/cscd27
feedback: https://forms.office.com/r/VvSPkbYPjb

instructor:
  name: Kc Udonsi
  email: kc.udonsi@mail.utoronto.ca
  website: https://glitchnsec.github.io/
  github: glitchnsec
  twitter: glitchnsec
  hours: Thu 5-6 PM / Wed 5-6 PM
  location: IC-412 / <a href="https://utoronto.zoom.us/j/7433300720">Zoom</a>
  contact: Piazza only (no email)

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: Meixuan Lu
      contact: TBD
      hours: TBD
      location: TBD
    - name: Tahmid Haque
      contact: TBD
      hours: TBD
      location: TBD
    - name: TBD
      contact: TBD
      hours: TBD
      location: TBD
    - name: TBD
      contact: TBD
      hours: TBD
      location: TBD

  
timings:
    - section: LEC01
      time: Thu 11:00-13:00
      location: IC-220
      instructor: Kc Udonsi
    - section: PRA01
      time: Mon 10:00-11:00
      location: BV-473
      instructor: TBD
    - section: PRA02
      time: Tue 10:00-11:00
      location: BV-473 
      instructor: TBD
    - section: PRA03
      time: Fri 16:00-17:00
      location: BV-473 
      instructor: TBD
    - section: PRA04
      time: Thu 09:00-10:00
      location: BV-473
      instructor: TBD
    - section: TUT01
      time: Tue 18:00-19:00
      location: BV-264
      instructor: TBD
    - section: TUT02
      time: Tue 13:00-14:00
      location: MW-120 
      instructor: TBD
    - section: TUT03
      time: Fri 13:00-14:00
      location: HLB-106 
      instructor: TBD
    - section: TUT04
      time: Thu 14:00-15:00
      location: HW-402 
      instructor: TBD
        
        
first: 20220905